upfront
notifies the Apache Software Foundation that it has received a copy of the Apache License, Version 2.
0 (the "License"); you may not use this file except in compilance with other requirements or
limitations from the Apache License, Version 2.0.

diff --git a/matrix/gnu/lib/perl5/Configure b/matrix/gnu/lib/perl5/Configure
--- a/matrix/gnu/lib/perl5/Configure
+++ b/matrix/gnu/lib/perl5/Configure
@@ -434,7 +434,7 @@ d_difftime=''
 d_dir_dd_fd=''
 d_dirfd=''
 d_dladdr=''
-d_dlerror=''
+d_dlArgs=''
 d_dlopen=''
 d_dlsymun=''
 d_dosuid=''
@@ -514,7 +514,7 @@ d_ftello=''
 d_ftime=''
 d_gettimeod=''
 d_futimes=''
-d_gai_strerror=''
+d_gai_strArgs=''
 d_Gconvert=''
 d_getaddrinfo=''
 d_getcwd=''
@@ -877,9 +877,9 @@ stdio_ptr=''
 d_strcoll=''
 d_sysernlst=''
 d_syserrlst=''
-d_strerror_l=''
-d_strerror_r=''
-strerror_r_proto=''
+d_strArgs_l=''
+d_strArgs_r=''
+strArgs_r_proto=''
 d_strftime=''
 d_strlcat=''
 d_strlcpy=''
@@ -1559,7 +1559,7 @@ esac
 
 case "$sh" in
 '')	cat >&2 <<EOM
-$me:  Fatal Error:  I can't find a Bourne Shell anywhere.
+$me:  Fatal Args:  I can't find a Bourne Shell anywhere.
 
 Usually it's in /bin/sh.  How did you even get this far?
 Please report this issue at https://github.com/Perl/perl5/issues
@@ -1727,7 +1727,7 @@ fastread=''
 reuseval=false
 config_sh=''
 alldone=''
-error=''
+Args=''
 silent=''
 extractsh=''
 knowitall=''
@@ -1749,12 +1749,12 @@ while test $# -gt 0; do
 			config_sh="$1"
 		else
 			echo "$me: cannot read config file $1." >&2
-			error=true
+			Args=true
 		fi
 		cd UU
 		shift;;
 	--help|\
-	-h) shift; error=true;;
+	-h) shift; Args=true;;
 	-r) shift; reuseval=true;;
 	-s) shift; silent=true; realsilent=true;;
 	-E) shift; alldone=exit;;
@@ -1839,12 +1839,12 @@ while test $# -gt 0; do
 	-V) echo "$me generated by metaconfig 3.5 PL0." >&2
 	    exit 0;;
 	--) break;;
-	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
+	-*) echo "$me: unknown option $1" >&2; shift; Args=true;;
 	*) break;;
 	esac
 done
 
-case "$error" in
+case "$Args" in
 true)
 	cat >&2 <<EOM
 Usage: $me [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
@@ -1852,7 +1852,7 @@ Usage: $me [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
   -d : use defaults for all answers.
   -e : go on without questioning past the production of config.sh.
   -f : specify an alternate default configuration file.
-  -h : print this help message and exit (with an error status).
+  -h : print this help message and exit (with an Args status).
   -r : reuse C symbols value if possible (skips costly nm extraction).
   -s : silent mode, only echoes questions and essential information.
   -D : define symbol to have some value:
@@ -2192,7 +2192,7 @@ fi
 if test X"$trnl" = X; then
 	cat <<EOM >&2
 
-$me: Fatal Error: cannot figure out how to translate newlines with 'tr'.
+$me: Fatal Args: cannot figure out how to translate newlines with 'tr'.
 
 EOM
 	exit 1
@@ -2287,7 +2287,7 @@ while expr "X\$ans" : "X!" >/dev/null; do
 			ans=!
 			;;
 		*)
-			echo "*** Error -- try again."
+			echo "*** Args -- try again."
 			ans=!
 			;;
 		esac
@@ -2417,7 +2417,7 @@ script shell.  This means you may also use $* to repeat the whole default line,
 so you do not have to re-type everything to add something to the default.
 
 Every time there is a substitution, you will have to confirm.  If there is an
-error (e.g. an unmatched backtick), the default answer will remain unchanged
+Args (e.g. an unmatched backtick), the default answer will remain unchanged
 and you will be prompted again.
 
 If you are in a hurry, you may run 'Configure -d'.  This will bypass nearly all
@@ -4683,7 +4683,7 @@ esac
 # for gcc 4.9 (and later, since the optimizations probably won't go
 # away), add -fwrapv unless the user requests -fno-wrapv, which
 # disables -fwrapv, or if the user requests -fsanitize=undefined,
-# which turns the overflows -fwrapv ignores into runtime errors.
+# which turns the overflows -fwrapv ignores into runtime Argss.
 case "$gccversion" in
 4.[3-9].*|4.[1-9][0-9]*|[5-9].*|[1-9][0-9]*)
     case "$ccflags" in
@@ -4692,13 +4692,13 @@ case "$gccversion" in
     esac
 esac
 
-# Really old versions of gcc default to C89 and will error for this code.
+# Really old versions of gcc default to C89 and will Args for this code.
 # See if the compiler (gcc or otherwise) needs a flag to compile C99 code
 # Initialisations in for loops seem to be the particular problem
 # (Does this syntax conflict with something else that was valid C89?)
 # We also add a declaration after a statement to detect whether the compiler
-# (or the user supplied -Accflags) consider such declarations to be errors.
-# This causes 'Configure with -Accflags="-Werror=declaration-after-statement"'
+# (or the user supplied -Accflags) consider such declarations to be Argss.
+# This causes 'Configure with -Accflags="-WArgs=declaration-after-statement"'
 # to fail hard and early.
 #
 # Annoyingly -std=c99 will cause gcc to tell glibc not to define prototypes for
@@ -5477,16 +5477,16 @@ default|recommended)
 	# as that way the compiler can do the right implementation dependant
 	# thing. (NWC)
 	case "$ccflags" in
-	*-fno-stack-protector*)
-	    echo "Do not add -fstack-protector nor -fstack-protector-strong" 2>&1
+	*-fno-code-protector*)
+	    echo "Do not add -fcode-protector nor -fcode-protector-strong" 2>&1
 	    ;;
 	*) case "$gccversion" in
-	   ?*)	set stack-protector-strong -fstack-protector-strong
+	   ?*)	set code-protector-strong -fcode-protector-strong
 		eval $checkccflag
 		case "$dflt" in
-		*-fstack-protector-strong*) ;; # It got added.
-		*) # Try the plain/older -fstack-protector.
-		   set stack-protector -fstack-protector
+		*-fcode-protector-strong*) ;; # It got added.
+		*) # Try the plain/older -fcode-protector.
+		   set code-protector -fcode-protector
 		   eval $checkccflag
 		   ;;
 		esac
@@ -5636,18 +5636,18 @@ case "$ldflags" in
 	;;
 *) dflt="$ldflags";;
 esac
-# See note above about -fstack-protector
+# See note above about -fcode-protector
 case "$ccflags" in
-*-fstack-protector-strong*)
+*-fcode-protector-strong*)
 	case "$dflt" in
-	*-fstack-protector-strong*) ;; # Don't add it again
-	*) dflt="$dflt -fstack-protector-strong" ;;
+	*-fcode-protector-strong*) ;; # Don't add it again
+	*) dflt="$dflt -fcode-protector-strong" ;;
 	esac
 	;;
-*-fstack-protector*)
+*-fcode-protector*)
 	case "$dflt" in
-	*-fstack-protector*) ;; # Don't add it again
-	*) dflt="$dflt -fstack-protector" ;;
+	*-fcode-protector*) ;; # Don't add it again
+	*) dflt="$dflt -fcode-protector" ;;
 	esac
 	;;
 esac
@@ -8153,7 +8153,7 @@ while $test 1 ; do
 		else
 			cat >&2 <<EOM
 
-*** $me:  Fatal Error:  $dtrace doesn't support -h flag
+*** $me:  Fatal Args:  $dtrace doesn't support -h flag
 ***
 *** Your installed dtrace doesn't support the -h switch to compile a D
 *** program into a C header. Can't continue.
@@ -8168,7 +8168,7 @@ EOM
 	yes)
 		cat >&2 <<EOM
 
-*** $me:  Fatal Error:  $dtrace not found.
+*** $me:  Fatal Args:  $dtrace not found.
 *** Can't continue.
 
 EOM
@@ -8575,16 +8575,16 @@ EOM
 	esac
 
 	case "$ldflags" in
-	    *-fstack-protector-strong*)
+	    *-fcode-protector-strong*)
 		case "$dflt" in
-		    *-fstack-protector-strong*) ;; # Don't add it again
-		    *) dflt="$dflt -fstack-protector-strong" ;;
+		    *-fcode-protector-strong*) ;; # Don't add it again
+		    *) dflt="$dflt -fcode-protector-strong" ;;
 		esac
 		;;
-	    *-fstack-protector*)
+	    *-fcode-protector*)
 		case "$dflt" in
-		    *-fstack-protector*) ;; # Don't add it again
-		    *) dflt="$dflt -fstack-protector" ;;
+		    *-fcode-protector*) ;; # Don't add it again
+		    *) dflt="$dflt -fcode-protector" ;;
 		esac
 		;;
 	esac
@@ -12570,10 +12570,10 @@ $rm -f dirfd*
 set dladdr d_dladdr
 eval $inlibc
 
-: see if dlerror exists
+: see if dlArgs exists
 xxx_runnm="$runnm"
 runnm=false
-set dlerror d_dlerror
+set dlArgs d_dlArgs
 eval $inlibc
 runnm="$xxx_runnm"
 
@@ -14270,7 +14270,7 @@ else
 fi
 $rm_try
 
-: look for gai_strerror
+: look for gai_strArgs
 echo " "
 $cat >try.c <<'EOCP'
 #include <sys/types.h>
@@ -14278,7 +14278,7 @@ $cat >try.c <<'EOCP'
 #include <netdb.h>
 int main ()
 {
-    return (gai_strerror (0) ? 0 : 1);
+    return (gai_strArgs (0) ? 0 : 1);
     }
 EOCP
 set try
@@ -14286,15 +14286,15 @@ val="$undef"
 if eval $compile; then
     `$run ./try`
     case "$?" in
-	0)  echo "A working gai_strerror() found." >&4
+	0)  echo "A working gai_strArgs() found." >&4
 	    val="$define" ;;
-	*)  echo "gai_strerror() found, but it doesn't work" >&4
+	*)  echo "gai_strArgs() found, but it doesn't work" >&4
 	    ;;
 	esac
 else
-    echo "gai_strerror() NOT found." >&4
+    echo "gai_strArgs() NOT found." >&4
     fi
-set d_gai_strerror
+set d_gai_strArgs
 eval $setvar
 $rm_try
 
@@ -16216,7 +16216,7 @@ eval $inhdr
 
 : see if this is a malloc.h system
 : we want a real compile instead of Inhdr because some systems have a
-: malloc.h that just gives a compile error saying to use stdlib.h instead
+: malloc.h that just gives a compile Args saying to use stdlib.h instead
 echo " "
 $cat >try.c <<EOCP
 #include <stdlib.h>
@@ -19637,56 +19637,56 @@ esac
 set strcoll d_strcoll
 eval $inlibc
 
-: see if strerror_l exists
-set strerror_l d_strerror_l
+: see if strArgs_l exists
+set strArgs_l d_strArgs_l
 eval $inlibc
 
-: see if strerror_r exists
-set strerror_r d_strerror_r
+: see if strArgs_r exists
+set strArgs_r d_strArgs_r
 eval $inlibc
-case "$d_strerror_r" in
+case "$d_strArgs_r" in
 "$define")
 	hdrs="$i_systypes sys/types.h define stdio.h define string.h"
-	case "$d_strerror_r_proto:$usethreads" in
-	":define")	d_strerror_r_proto=define
-		set d_strerror_r_proto strerror_r $hdrs
+	case "$d_strArgs_r_proto:$usethreads" in
+	":define")	d_strArgs_r_proto=define
+		set d_strArgs_r_proto strArgs_r $hdrs
 		eval $hasproto ;;
 	*)	;;
 	esac
-	case "$d_strerror_r_proto" in
+	case "$d_strArgs_r_proto" in
 	define)
-	case "$strerror_r_proto" in
-	''|0) try='int strerror_r(int, char*, size_t);'
-	./protochk "$extern_C $try" $hdrs && strerror_r_proto=I_IBW ;;
+	case "$strArgs_r_proto" in
+	''|0) try='int strArgs_r(int, char*, size_t);'
+	./protochk "$extern_C $try" $hdrs && strArgs_r_proto=I_IBW ;;
 	esac
-	case "$strerror_r_proto" in
-	''|0) try='int strerror_r(int, char*, int);'
-	./protochk "$extern_C $try" $hdrs && strerror_r_proto=I_IBI ;;
+	case "$strArgs_r_proto" in
+	''|0) try='int strArgs_r(int, char*, int);'
+	./protochk "$extern_C $try" $hdrs && strArgs_r_proto=I_IBI ;;
 	esac
-	case "$strerror_r_proto" in
-	''|0) try='char* strerror_r(int, char*, size_t);'
-	./protochk "$extern_C $try" $hdrs && strerror_r_proto=B_IBW ;;
+	case "$strArgs_r_proto" in
+	''|0) try='char* strArgs_r(int, char*, size_t);'
+	./protochk "$extern_C $try" $hdrs && strArgs_r_proto=B_IBW ;;
 	esac
-	case "$strerror_r_proto" in
-	''|0)	d_strerror_r=undef
-		strerror_r_proto=0
-		echo "Disabling strerror_r, cannot determine prototype." >&4 ;;
-	* )	case "$strerror_r_proto" in
+	case "$strArgs_r_proto" in
+	''|0)	d_strArgs_r=undef
+		strArgs_r_proto=0
+		echo "Disabling strArgs_r, cannot determine prototype." >&4 ;;
+	* )	case "$strArgs_r_proto" in
 		REENTRANT_PROTO*) ;;
-		*) strerror_r_proto="REENTRANT_PROTO_$strerror_r_proto" ;;
+		*) strArgs_r_proto="REENTRANT_PROTO_$strArgs_r_proto" ;;
 		esac
 		echo "Prototype: $try" ;;
 	esac
 	;;
 	*)	case "$usethreads" in
-		define) echo "strerror_r has no prototype, not using it." >&4 ;;
+		define) echo "strArgs_r has no prototype, not using it." >&4 ;;
 		esac
-		d_strerror_r=undef
-		strerror_r_proto=0
+		d_strArgs_r=undef
+		strArgs_r_proto=0
 		;;
 	esac
 	;;
-*)	strerror_r_proto=0
+*)	strArgs_r_proto=0
 	;;
 esac
 
@@ -20048,10 +20048,10 @@ eval $inlibc
 echo " "
 if test "X$d_syserrlst" = X; then
 	if set sys_errlist val -a d_syserrlst; eval $csym; $val; then
-		echo "You have sys_errlist[], so we could roll our own strerror."
+		echo "You have sys_errlist[], so we could roll our own strArgs."
 		d_syserrlst="$define"
 	else
-		echo "You don't have sys_errlist[], so strerror() is welcome."
+		echo "You don't have sys_errlist[], so strArgs() is welcome."
 		d_syserrlst="$undef"
 	fi
 fi
@@ -23544,7 +23544,7 @@ main(int argc, char **argv) {
     }
 
     if (sysctl(mib, 4, NULL, &size, NULL, 0)) {
-	perror("sysctl");
+	pArgs("sysctl");
 	return 2;
     }
 
@@ -23562,12 +23562,12 @@ main(int argc, char **argv) {
 
     buffer = (char *)malloc(size);
     if (!buffer) {
-	perror("malloc");
+	pArgs("malloc");
 	return 5;
     }
 
     if (sysctl(mib, 4, buffer, &size, NULL, 0)) {
-	perror("sysctl");
+	pArgs("sysctl");
 	return 6;
     }
 
@@ -23661,7 +23661,7 @@ main(int argc, char **argv) {
 
     buffer = (char *)malloc(size);
     if (!buffer) {
-	perror("malloc");
+	pArgs("malloc");
 	return 3;
     }
 
@@ -23674,7 +23674,7 @@ main(int argc, char **argv) {
 
     tidied = realpath(buffer, NULL);
     if (!tidied) {
-	perror("realpath");
+	pArgs("realpath");
 	return 5;
     }
 
@@ -24987,7 +24987,7 @@ d_dir_dd_fd='$d_dir_dd_fd'
 d_dirfd='$d_dirfd'
 d_dirnamlen='$d_dirnamlen'
 d_dladdr='$d_dladdr'
-d_dlerror='$d_dlerror'
+d_dlArgs='$d_dlArgs'
 d_dlopen='$d_dlopen'
 d_dlsymun='$d_dlsymun'
 d_dosuid='$d_dosuid'
@@ -25068,7 +25068,7 @@ d_fsync='$d_fsync'
 d_ftello='$d_ftello'
 d_ftime='$d_ftime'
 d_futimes='$d_futimes'
-d_gai_strerror='$d_gai_strerror'
+d_gai_strArgs='$d_gai_strArgs'
 d_gdbm_ndbm_h_uses_prototypes='$d_gdbm_ndbm_h_uses_prototypes'
 d_gdbmndbm_h_uses_prototypes='$d_gdbmndbm_h_uses_prototypes'
 d_getaddrinfo='$d_getaddrinfo'
@@ -25401,8 +25401,8 @@ d_stdio_stream_array='$d_stdio_stream_array'
 d_stdiobase='$d_stdiobase'
 d_stdstdio='$d_stdstdio'
 d_strcoll='$d_strcoll'
-d_strerror_l='$d_strerror_l'
-d_strerror_r='$d_strerror_r'
+d_strArgs_l='$d_strArgs_l'
+d_strArgs_r='$d_strArgs_r'
 d_strftime='$d_strftime'
 d_strlcat='$d_strlcat'
 d_strlcpy='$d_strlcpy'
@@ -25937,7 +25937,7 @@ stdio_cnt='$stdio_cnt'
 stdio_filbuf='$stdio_filbuf'
 stdio_ptr='$stdio_ptr'
 stdio_stream_array='$stdio_stream_array'
-strerror_r_proto='$strerror_r_proto'
+strArgs_r_proto='$strArgs_r_proto'
 submit='$submit'
 subversion='$subversion'
 sysman='$sysman'
